const CLEARLY_MESSAGE = {
  messages: {
    'clip.pop.feature.remove': { en: 'Delete', es: 'Borrar', zh: '新增', 'zh-TW': '新增' },
    'clip.pop.feature.webapp': { en: 'Web App', es: 'Aplicación Web', zh: 'Web App', 'zh-TW': 'Web App' },
    'clip.pop.feature.shortcuts': { en: 'Shortcuts', es: 'Atajos', zh: '新增', 'zh-TW': '新增' },
    'clip.pop.add': { en: 'Add', es: 'Agregar', zh: '新增', 'zh-TW': '新增' },
    // 收藏成功
    'clip.pop.collect.success': { en: 'Clip Success', es: 'Clip de éxito', zh: '收藏成功', 'zh-TW': '收藏成功' },
    // 新增标签
    'clip.pop.tag.search': { en: 'Search Tag', es: 'Etiqueta de búsqueda', zh: '搜索标签', 'zh-TW': '搜索標籤' },
    // 新增标签
    'clip.pop.tag.add': { en: 'Add Tag', es: 'Añadir etiqueta', zh: '新增标签', 'zh-TW': '新增標籤' },
    // 删除成功
    'clip.pop.remove.success': { en: 'Removed', es: 'Abrir claramente', zh: '删除成功', 'zh-TW': '刪除成功' },
    'clip.pop.remove.unsaved': { en: 'Unsaved please wait', es: 'No guardado por favor espere', zh: '未保存请稍候', 'zh-TW': '未保存請稍候' },
    'content.tip.open': { en: 'Open Clearly', es: 'Abrir claramente', zh: '打开Clearly', 'zh-TW': '打開 Clearly' },
    'content.tip.notsupport': { en: 'Clearly not support for this page', es: 'Claramente no es compatible con esta página', zh: 'Clearly 不支持此页面', 'zh-TW': 'Clearly 不支持此頁面' },
    'content.tip.loginok': { en: 'You already loged in Clearly', es: 'Ya has iniciado sesión en Clearly', zh: '你已经登录了 Clearly', 'zh-TW': '你已經登錄了 Clearly' },
    'content.tip.dismiss': { en: 'Dismiss', es: 'Despedir', zh: '忽略', 'zh-TW': '忽略' },
    'content.tip.confirm': { en: 'Confirm', es: 'Confirma', zh: '确认', 'zh-TW': '確認' },
    'app.article.estimated': { en: '$1 Estimated', es: '$1 Estimado', zh: '预计时间 $1', 'zh-TW': '預計時間 $1' },
    'app.article.wordscount': { en: '$1 Words', es: '$1 Palabras', zh: '字数 $1', 'zh-TW': '字數 $1' },
    'app.article.lang': { en: '$1 Language', es: '$1 Idioma', zh: '语言 $1', 'zh-TW': '語言 $1' },
    'app.autoopen.title': { en: 'Auto open', es: 'Auto abierto', zh: '自动开启', 'zh-TW': '自動開啟' },
    'app.outline.links': { en: 'Links', es: 'Enlaces', zh: '链接', 'zh-TW': '鏈接' },
    'app.feedback.title': { en: 'Does Clearly works fine?', es: 'Claramente funciona bien?', zh: 'Clearly 展示是否正常？', 'zh-TW': 'Clearly 展示是否正常？' },
    'app.feedback.received': { en: 'Thanks for your feedback', es: 'Gracias por tus comentarios', zh: '感谢你反馈', 'zh-TW': '感謝你反饋' },
    'app.feedback.help': { en: 'Help Clearly Reader be better', es: 'Ayuda claramente el lector será mejor', zh: '帮助 Clearly 变得更好', 'zh-TW': '幫助 Clearly 變得更好' },
    'app.feedback.stars': { en: 'Give stars', es: 'Dar estrellas', zh: '给好评', 'zh-TW': '給好評' },
    'app.feedback.tip': { en: 'Tips', es: 'Puntas', zh: '小提示', 'zh-TW': '小提示' },
    'app.tool.copyas': { en: 'Copy as', es: 'Copiar como', zh: '复制为', 'zh-TW': '複製為' },
    'app.tool.exportto': { en: 'Export to', es: 'Exportar a', zh: '导出为', 'zh-TW': '導出為' },
    'app.tool.sendas': { en: 'Send as', zh: '发送为' },
    'app.style.title': { en: 'Style Settings', es: 'Configuración de estilo', zh: '样式设置', 'zh-TW': '樣式設置' },
    'app.style.uitab': { en: 'UI', es: 'IU', zh: '界面', 'zh-TW': '界面' },
    'app.style.displaytab': { en: 'Display elements', es: 'Mostrar elementos', zh: '显示元素', 'zh-TW': '顯示元素' },
    'app.style.pagewidth': { en: 'Page width', es: 'Ancho de página', zh: '页宽', 'zh-TW': '頁寬' },
    'app.style.autotheme': { en: 'Auto theme', es: 'Tema automático', zh: '启用自动主题', 'zh-TW': '啟用自動主題' },
    'app.style.theme': { en: 'Theme', es: 'Tema', zh: '主题', 'zh-TW': '主題' },
    'app.style.daytheme': { en: 'Day theme', es: 'Tema de día', zh: '白天主题', 'zh-TW': '白天主題' },
    'app.style.nighttheme': { en: 'Night theme', es: 'Tema nocturno', zh: '夜间主题', 'zh-TW': '夜間主題' },
    'app.style.fontsize': { en: 'Font size', es: 'Tamaño de fuente', zh: '字体大小', 'zh-TW': '字體大小' },
    'app.style.codehighlight': { en: 'Code highlight', es: 'Resaltado del código', zh: '代码高亮', 'zh-TW': '代碼高亮' },
    'app.style.openlink': { en: 'Open links in new tab', es: 'Abrir enlaces en la pestaña nueva', zh: '新页面打开链接', 'zh-TW': '新頁面打開鏈接' },
    'app.style.outline': { en: 'Extract outline', es: 'Extraer esquema', zh: '提取大纲', 'zh-TW': '提取大綱' },
    'app.style.background': { en: 'Background', es: 'Antecedentes', zh: '启用背景', 'zh-TW': '啟用背景' },
    'app.style.fonts': { en: 'Fonts', es: 'Fonts', zh: '字体', 'zh-TW': '字體' },
    'app.style.links': { en: 'Extract links', es: 'Extraer enlaces', zh: '提取链接', 'zh-TW': '提取鏈接' },
    'app.style.popmenutoggle': { en: 'Popmenu controls', es: 'Popmenu controls', zh: '弹出菜单控制', 'zh-TW': '彈出菜單控制' },
    'app.style.wikimenu': { en: 'Wiki lookup', es: 'Wiki lookup', zh: '维基查找', 'zh-TW': '維基查找' },
    'app.style.searchmenu': { en: 'Privacy search', es: 'Privacy search', zh: '隐私搜索', 'zh-TW': '隱私搜索' },
    'app.translate.prefix': { en: 'To', es: 'a', zh: '到', 'zh-TW': '到' },
    'app.menu.translate': { en: 'Translate', es: 'Traducir', zh: '翻译', 'zh-TW': '翻譯' },
    'app.menu.copy': { en: 'Copy', es: 'Copiar', zh: '复制', 'zh-TW': '複製' },
    'app.menu.speak': { en: 'Speak', es: 'Hablar', zh: '朗读', 'zh-TW': '朗讀' },
    'app.menu.search': { en: 'Search', es: 'Búsqueda', zh: '搜索', 'zh-TW': '搜索' },
    'app.menu.wiki': { en: 'Wiki', es: 'Wiki', zh: '维基', 'zh-TW': '維基' },
    'app.about.title': { en: 'About', es: 'Sobre', zh: '关于', 'zh-TW': '關於' },
    'app.about.appversion': { en: 'App version', es: 'Version de aplicacion', zh: '应用版本', 'zh-TW': '應用版本' },
    'app.about.fullchangelogs': { en: 'Check full changelogs', es: 'Cambios completos', zh: '查看完整版本记录', 'zh-TW': '查看完整版本記錄' },
    'app.about.configversion': { en: 'Config version', es: 'Versión de configuración', zh: '配置版本', 'zh-TW': '配置版本' },
    'app.about.feedback': { en: 'Give a feedback', es: 'Dar comentarios', zh: '给我们反馈', 'zh-TW': '給我們反饋' },
    'app.about.reportbug': { en: 'Report a bug', es: 'Reportar un error', zh: '反馈问题', 'zh-TW': '反饋問題' },
    'app.about.givestars': { en: 'Give stars', es: 'Dar estrellas', zh: '给好评', 'zh-TW': '給好評' },
    'app.about.links': { en: 'More Links', es: 'Más enlaces', zh: '更多链接', 'zh-TW': '更多鏈接' },
    'app.about.watchvideo': { en: 'Watch video', es: 'Ver video', zh: '观看视频', 'zh-TW': '觀看視頻' },
    'app.about.contact': { en: 'Contact US', es: 'Contáctenos', zh: '联系我们', 'zh-TW': '聯繫我們' },
    'app.about.buymeacoffee': { en: 'Buy me a coffee', es: 'Cómprame un café', zh: '送杯咖啡', 'zh-TW': '送杯咖啡' },
    'app.about.products': { en: 'Our products', es: 'Nuestros productos', zh: '我们的产品', 'zh-TW': '我們的產品' },
    'app.about.copyright': { en: 'Created by LESSLAB', es: 'Creado por LESSLAB', zh: '由 LESSLAB 创造', 'zh-TW': '由 LESSLAB 創造' },
    'app.about.checkconfigversion': { en: 'Check version', es: 'Verificar la versión', zh: '检查配置更新', 'zh-TW': '檢查配置更新' },
    'app.speak.voice': { en: 'Voice', es: 'Voz', zh: '声音', 'zh-TW': '聲音' },
    'app.custom.title': { en: 'Theme Customization', es: 'Personalización del tema', zh: '自定义主题', 'zh-TW': '自定義主題' },
    'app.custom.maincolor': { en: 'Reader color', es: 'Color lector', zh: '阅读颜色', 'zh-TW': '閱讀顏色' },
    'app.custom.bgcolor': { en: 'Background color', es: 'Color de fondo', zh: '背景色', 'zh-TW': '背景色' },
    'app.style.fontcolor': { en: 'Font color', es: 'Color de fuente', zh: '字体颜色', 'zh-TW': '字體顏色' },
    'app.style.codebgcolor': { en: 'Code background color', es: 'Código de fondo de fondo', zh: '代码背景色', 'zh-TW': '代碼背景色' },
    'app.style.spacing': { en: 'Font spacing', es: 'Espaciado de letras', zh: '字间距', 'zh-TW': '字間距' },
    'app.style.lineheight': { en: 'Line height', es: 'Altura de la línea', zh: '行高' },
    'app.style.roundcorner': { en: 'Round corner', es: 'Esquina redonda', zh: '圆角', 'zh-TW': '圓角' },
    'app.style.booklayout': { en: 'Book layout', es: 'Diseño de libros', zh: '图书布局', 'zh-TW': '圖書佈局' },
    'app.setting.showtip': { en: 'Show tip when readable', es: 'Consejo abierto cuando sea legible', zh: '可读时提示开启', 'zh-TW': '可讀時提示開啟' },
    'app.setting.translatelang': { en: 'Translate language', es: 'Lenguaje Traducir', zh: '翻译语言', 'zh-TW': '翻譯語言' },
    'app.setting.title': { en: 'Settings', es: 'Ajustes', zh: '设置', 'zh-TW': '設置' },
    'app.setting.shortcuts': { en: 'Shortcuts', es: 'Atajos', zh: '快捷键', 'zh-TW': '快捷鍵' },
    'app.setting.disablebrand': { en: 'Disable brand elements', zh: '不显示品牌相关元素', 'zh-TW': '不顯示品牌相關元素' },
    'app.setting.disableexportbrand': { en: 'Disable Export Footer', zh: '导出文件不显示品牌', 'zh-TW': '導出文件不顯示品牌' },
    'app.setting.shortcutsedit': { en: 'Click to view/edit shortcuts', es: 'El valor predeterminado es <opción/alt + r>, editar accesos directos', zh: '点击查看/修改快捷键', 'zh-TW': '點擊查看/修改快捷鍵' },
    'app.setting.speechmsengine': { en: 'Microsoft AI Speech Engine', zh: '微软AI语音引擎', 'zh-TW': '微軟AI語音引擎' },
    'app.setting.clippopup': { en: 'Clip Popup', es: 'Clip emergente', zh: '剪藏浮层', 'zh-TW': '剪藏浮層' },
    'app.clip.share': { en: 'Online share', es: 'Compartir en línea', zh: '在线分享', 'zh-TW': '在線分享' },
    'app.clip.sharetip': { en: 'Create an online URL to share', es: 'Crear una URL en línea para compartir', zh: '为你提供一个在线URL分享', 'zh-TW': '為你提供一個在線URL分享' },
    'app.clip.rss': { en: 'Read via RSS', es: 'Leer vía RSS', zh: '通过RSS阅读', 'zh-TW': '通過RSS閱讀' },
    'app.clip.rsstip': { en: 'Read in your favorite RSS reader', es: 'Lea a través de su lector de RSS', zh: '通过你的RSS阅读器阅读', 'zh-TW': '通過你的RSS閱讀器閱讀' },
    'app.clip.podcast': { en: 'Listen via Poscast', es: 'Escúchalo en Poscast', zh: '生成播客', 'zh-TW': '生成播客' },
    'app.clip.podcasttip': { en: 'Listen in your favorite podcast app', es: 'Escucha en tu aplicación de podcast favorita', zh: '使用你喜欢的播客软件收听', 'zh-TW': '使用你喜歡的播客軟件收聽' },
    'app.clip.audio': { en: 'Download as MP3', es: 'Descargar como mp3', zh: '下载为MP3', 'zh-TW': '下載為MP3' },
    'app.clip.audiotip': { en: 'Download this article as AI speech MP3 file', es: 'Descargue este artículo como archivo mp3 de discurso ai', zh: '下载AI人声朗读的MP3音频文件', 'zh-TW': '下載AI人聲朗讀的MP3音頻文件' },
    'app.clip.epub': { en: 'Download as EPUB', es: 'Descargar como EPUB', zh: '下载为EPUB', 'zh-TW': '下載為EPUB' },
    'app.clip.epubtip': { en: 'Download this article as EPUB file', es: 'Descargue este artículo como archivo EPUB', zh: '下载为EPUB电子书', 'zh-TW': '下載為EPUB電子書' },
    'app.clip.epubbtn': { en: 'Download', es: 'Descargar', zh: '下载', 'zh-TW': '下載' },
    'app.clip.kindle': { en: 'Send to Kindle', es: 'Enviar a Kindle', zh: '发送到Kindle', 'zh-TW': '發送到Kindle' },
    'app.clip.kindletip': { en: 'Send this article to your Kindle device', es: 'Envíe este artículo a su dispositivo Kindle', zh: '发送到你的Kindle设备', 'zh-TW': '發送到你的Kindle設備' },
    'app.clip.kindlebtn': { en: 'Send', es: 'Enviar', zh: '发送', 'zh-TW': '發送' },
    'app.kindle.title': { en: 'Send to Kindle', es: 'Enviar a Kindle', zh: '发送到Kindle', 'zh-TW': '發送到Kindle' },
    'app.kindle.email': { en: 'Kindle Email', es: 'Correo electrónico Kindle', zh: 'Kindle邮箱', 'zh-TW': 'Kindle郵箱' },
    'app.kindle.btn': { en: 'Send', es: 'Enviar', zh: '发送', 'zh-TW': '發送' },
    'app.kindle.tip': { en: 'Please add "kindle@clearlyreader.com" to you kindle "Approved Personal Document E-mail List" on https://www.amazon.com/hz/mycd/myx#/home/settings/payment', zh: '请在 https://www.amazon.com/hz/mycd/myx#/home/settings/payment 添加 "kindle@clearlyreader.com" 到你的Kindle "Approved Personal Document E-mail List" 列表中' },
    'app.clip.clip': { en: 'Clip to cloud', es: 'Clip a la nube', zh: '剪藏到云端', 'zh-TW': '剪藏到雲端' },
    'app.clip.clipdes': { en: 'Clip snapshot to cloud', es: 'Guarda este artículo en la nube y', zh: '剪藏文章快照到云端', 'zh-TW': '剪藏文章快照到云端' },
    'app.clip.clipbtn': { en: 'Clip', es: 'Acortar', zh: '剪藏', 'zh-TW': '剪藏' },
    'app.clip.clipdeletebtn': { en: 'Delete', es: 'Borrar', zh: '删除', 'zh-TW': '刪除' },
    'app.clip.summary': { en: 'AI Summary', es: 'Resumen de IA', zh: 'AI总结', 'zh-TW': 'AI總結' },
    'app.clip.summarytip': { en: 'Summarize article with AI', es: 'Resumir artículo con IA', zh: '通过AI总结和简化', 'zh-TW': '通過AI總結和簡化' },
    'app.clip.intro': { en: '[CLIP] is a online store service, when you use your content will store online.', zh: 'CLIP 是一个在线存储服务，仅提供存储和转换服务', 'zh-TW': 'CLIP 是一個在線存儲服務，僅提供存儲和轉換服務' },
    'app.clip.rssbtn': { en: 'Add to RSS', es: 'Agregar a RSS', zh: '添加到RSS', 'zh-TW': '添加到RSS' },
    'app.clip.podcastbtn': { en: 'Add to Podcast', es: 'Agregar a podcast', zh: '添加到播客', 'zh-TW': '添加到播客' },
    'app.clip.audiobtn': { en: 'Download MP3', es: 'Descargar mp3', zh: '下载MP3', 'zh-TW': '下載MP3' },
    'app.clip.summarybtn': { en: 'Summarize', es: 'Resumen', zh: '总结', 'zh-TW': '總結' },
    'app.clip.summarybtnpending': { en: 'Summarizing', es: 'Resumen', zh: '总结中', 'zh-TW': '總結中' },
    'app.clip.summarybtndone': { en: 'More summaries', es: 'Más resúmenes', zh: '更多总结', 'zh-TW': '更多總結' },
    'app.clip.tag': { en: 'Keywords Reading', es: 'Lectura de palabras clave', zh: '关键词阅读', 'zh-TW': '關鍵詞閱讀' },
    'app.clip.tagtip': { en: 'Reading the keywords the help you read quickly', zh: '通过关键词帮助你快速阅读', 'zh-TW': '通過關鍵詞幫助你快速閱讀' },
    'app.clip.tagbtn': { en: 'Show Keywords', zh: '显示关键词', 'zh-TW': '顯示關鍵詞' },
    'app.clip.tagbtnclose': { en: 'Close Keywords', zh: '关闭关键词', 'zh-TW': '關閉關鍵詞' },
    'app.clip.marksUnit': { en: ' marks', zh: '标记', 'zh-TW': '標記' },
    'app.clip.upgradeintro': { en: 'Upgrade to PREMIUM to unlock all features', es: 'Actualice a PREMIUM para desbloquear todas las funciones', zh: '升级解锁全部功能', 'zh-TW': '升級解鎖全部功能' },
    'app.clip.upgradebtn': { en: 'Upgrade to PREMIUM', es: 'Mejorado a Premium', zh: '升级订阅版', 'zh-TW': '升級訂閱版' },
    'app.clip.addbookmark': { en: 'Add', es: 'Agregar', zh: '添加书签', 'zh-TW': '添加書籤' },
    'app.clip.delbookmark': { en: 'Delete', es: 'Borrar', zh: '删除书签', 'zh-TW': '刪除書籤' },
    'app.clip.bookmark': { en: 'Bookmark', es: 'Marcador', zh: '书签', 'zh-TW': '書籤' },
    'app.clip.bookmarktip': { en: 'Bookmark to read it later', es: 'Marcar para leerlo más tarde', zh: '添加书签稍后读', 'zh-TW': '添加書籤稍後讀' },
    'app.clip.autoclip': { en: 'Clip automatically', es: 'Clip automáticamente', zh: '自动剪藏', 'zh-TW': '自動剪藏' },
    'app.css.title': { en: 'CSS', es: 'CSS', zh: 'CSS', 'zh-TW': 'CSS' },
    'app.css.resetbtn': { en: 'Reset', es: 'Reiniciar', zh: '重置', 'zh-TW': '重置' },
    'app.css.intro': { en: 'You shoud known CSS code before you change it.', es: 'Debe conocer el código CSS antes de cambiarlo.', zh: '修改之前请确保你会使用CSS代码', 'zh-TW': '修改之前請確保你會使用CSS代碼' },
    'app.upgrade.link': { en: 'Unlock all PRO features', es: 'Desbloquear todas las características de Pro', zh: '解锁专业版功能', 'zh-TW': '解鎖專業版功能' },
    'app.upgrade.btn': { en: 'PRO/PREMIUM comparison', es: 'Comparación de PRO/PREMIUM', zh: '专业版/订阅版对比', 'zh-TW': '專業版/訂閱版對比' },
    'app.upgrade.active': { en: 'Login account to activate', es: 'Inicie sesión en la cuenta para activar', zh: '登录账号激活', 'zh-TW': '登錄賬號激活' },
    'app.setting.lang': { en: 'UI Language', es: 'Lenguaje de interfaz', zh: '界面语言', 'zh-TW': '界面語言' },
    'app.setting.account': { en: 'Account', es: 'Cuenta', zh: '账号', 'zh-TW': '帳號' },
    'app.setting.syncconfig': { en: 'Sync config', es: 'Sincronizar', zh: '同步配置', 'zh-TW': '同步配置' },
    'app.setting.syncconfigversion': { en: 'Last update', es: 'Última actualización', zh: '最后更新', 'zh-TW': '最後更新' },
    'app.setting.syncconfigconfict': { en: 'Sync Conflict', es: 'Conflicto de sincronización', zh: '同步冲突', 'zh-TW': '同步衝突' },
    'app.setting.syncconfiglocal': { en: 'Use local', es: 'Usar local', zh: '使用本地', 'zh-TW': '使用本地' },
    'app.setting.syncconfigonline': { en: 'Use online', es: 'Usar en línea', zh: '使用在线', 'zh-TW': '使用在線' },
    'app.setting.paragraphtranslate': { en: 'PAR-Translate Button', es: 'Botón de traducción de párrafo', zh: '段落翻译按钮', 'zh-TW': '段落翻譯按鈕' },
    'app.account.title': { en: 'Account', es: 'Cuenta', zh: '账号', 'zh-TW': '帳號' },
    'app.account.email': { en: 'Email', es: 'Correo electrónico', zh: '邮箱', 'zh-TW': '電郵' },
    'app.account.planid': { en: 'Member Plan', es: 'Plan miembro', zh: '会员计划', 'zh-TW': '會員計畫' },
    'app.account.planexpiredat': { en: 'Member Expire Date', es: 'Fecha de vencimiento del miembro', zh: '会员到期时间', 'zh-TW': '會員到期時間' },
    'app.account.loginemail': { en: 'Login Email', es: 'Ingreso (correo', zh: '登录邮箱', 'zh-TW': '登入郵箱' },
    'app.account.logincode': { en: 'Login Code', es: 'Código de inicio de sesión', zh: '登录验证码', 'zh-TW': '登入驗證碼' },
    'app.account.codetip': { en: 'A vertification code has been sent to your email accont.', es: 'Se ha enviado un código de verificación a su cuenta de correo electrónico.', zh: '请前往邮箱查看已经发送的验证码。', 'zh-TW': '請前往郵箱查看已經發送的驗證碼。' },
    'app.account.loginbtn': { en: 'Signup / Login', es: 'Acceso', zh: '注册 / 登录', 'zh-TW': '註冊 / 登入' },
    'app.account.logoutbtn': { en: 'Logout', es: 'Cerrar sesión', zh: '登出', 'zh-TW': '登出' },
    'app.account.codesent': { en: 'Please check your email (includes spam folder)', zh: '请检查你的邮箱（包括垃圾邮件）', 'zh-TW': '請檢查你的郵箱（包括垃圾郵件）' },
    'app.account.loginrequired': { en: 'Please login first', es: 'Primero inicie sesión', zh: '请先登录', 'zh-TW': '請先登入' },
    'app.style.latex': { en: 'LaTeX math format', es: 'Formato matemático LaTeX', zh: 'LaTeX 数学公式', 'zh-TW': 'LaTeX 數學公式' },
    'app.style.showvideo': { en: 'Display videos', es: 'Mostrar videos', zh: '显示视频', 'zh-TW': '顯示視頻' },
    'app.shortcut.toggle_k': { en: 'Default is <⌘ / ALT + R>, Click to Edit', es: 'El valor predeterminado es <⌘ / alt + r>, editar accesos directos', zh: '默认为 <⌘ / ALT + R>，点击修改', 'zh-TW': '預設為 <⌘ / ALT + R>，點擊修改' },
    'app.shortcut.toggle': { en: 'Toggle', es: 'Palanca', zh: '开关', 'zh-TW': '開關' },
    'app.shortcut.prev': { en: 'Previous Page', es: 'La página anterior', zh: '上一页', 'zh-TW': '上一頁' },
    'app.shortcut.next': { en: 'Next Page', es: 'Siguiente página', zh: '下一页', 'zh-TW': '下一頁' },
    'app.shortcut.home': { en: 'First Page', es: 'Primera página', zh: '首页', 'zh-TW': '首頁' },
    'app.shortcut.last': { en: 'Last Page', es: 'Última página', zh: '末页', 'zh-TW': '尾頁' },
    'app.shortcut.speak': { en: 'Speak', es: 'Hablar', zh: '朗读', 'zh-TW': '朗讀' },
    'app.shortcut.print': { en: 'Print', es: 'Imprimir', zh: '打印', 'zh-TW': '列印' },
    'app.shortcut.clip': { en: 'CLIP', zh: '剪藏' },
    'app.shortcut.bookview': { en: 'Toogle Book Layout', es: 'Diseño del libro de Toogle', zh: '开关图书布局', 'zh-TW': '開關圖書佈局' },
    'app.shortcut.escape': { en: 'Return/Exit', es: 'Regresar/salir', zh: '返回/退出' },
    'app.shortcut.help': { en: 'Help', es: 'Ayudar', zh: '帮助', 'zh-TW': '幫助' },
    'app.shortcut.export': { en: 'Export/Copy', es: 'Exportar/copiar', zh: '导出/复制', 'zh-TW': '導出/複製' },
    'app.shortcut.theme': { en: 'Theme Settings', es: 'Configuración de temas', zh: '主题设置', 'zh-TW': '主題設置' },
    'app.shortcut.title': { en: 'Shortcuts', es: 'Atajos', zh: '快捷键列表', 'zh-TW': '快捷鍵列表' },
    'app.shortcut.report': { en: 'Report bug', es: 'Reportar un error', zh: '报告问题', 'zh-TW': '報告問題' },
    'app.upgrade.title': { en: 'Upgrade', es: 'Potenciar', zh: '升级', 'zh-TW': '升級' },
    'app.upgrade.feature1': { en: 'Customizition: Themes, Fonts, Size, Style, Auto dark etc', es: 'Personalización: temas, fuentes, tamaño, estilo, oscuro automático, etc.', zh: '自定义：主题、字体、大小、样式、自动切换夜间模式等', 'zh-TW': '自定義：主題、字體、大小、樣式、自動切換夜間模式等' },
    'app.upgrade.feature2': { en: 'Advanced support: LaTex math format, Display videos etc.', es: 'Soporte avanzado: formato matemático LaTex, mostrar videos, etc.', zh: '高级支持：LaTex 数学公式、显示视频等', 'zh-TW': '高級支持：LaTex 數學公式、顯示視頻等' },
    'app.upgrade.feature3': { en: 'Export formats: customized PDF, Office word, Markdown etc.', es: 'Formatos de exportación: PDF personalizado, Office word, Markdown, etc.', zh: '导出格式：自定义 PDF、Office word、Markdown 等', 'zh-TW': '導出格式：自定義 PDF、Office word、Markdown 等' },
    'app.upgrade.feature4': { en: 'Customize TTS voices, Microsoft TTS voices', es: 'Personalizar voces TTS, voces TTS de Microsoft', zh: '自定义 TTS 语音、微软 TTS 语音', 'zh-TW': '自定義 TTS 語音、微軟 TTS 語音' },
    'app.upgrade.feature5': { en: 'Reading features: Book layout, AI summary, Highlight annotations, Wiki etc', es: 'Características de lectura: diseño del libro, resumen de IA, anotaciones de resaltado, Wiki, etc.', zh: '阅读特性：图书布局、AI 摘要、高亮注释、WIKI 等', 'zh-TW': '閱讀特性：圖書佈局、AI 摘要、高亮注釋、WIKI 等' },
    'app.upgrade.feature6': { en: 'Cloud features: Sync config, bookmarks, clips, listen to RSS/Podcasts etc.', es: 'Características en la nube: sincronizar configuración, marcadores, clips, agregar a RSS / Podcasts, etc.', zh: '云特性：同步配置、书签、剪藏、添加到 RSS/Podcasts 等', 'zh-TW': '雲特性：同步配置、書籤、剪藏、添加到 RSS/Podcasts 等' },
    'app.upgrade.feature7': { en: 'Remove footer and brand', es: 'Retire el pie de página y la marca', zh: '移除底部和品牌标志', 'zh-TW': '移除底部和品牌標誌' },
    'app.upgrade.tippro': { en: 'You need upgrade to use this feature', es: 'Necesita actualizar para usar esta función', zh: '需要升级 PRO 才能使用这个功能', 'zh-TW': '需要升級 PRO 才能使用這個功能' },
    'app.upgrade.tippremium': { en: 'Premium is only available for invited customers', es: 'Premium solo está disponible para clientes invitados', zh: 'PREMIUM 功能仅限受邀请用户使用', 'zh-TW': 'PREMIUM 功能僅限受邀請用戶使用' },
    'app.upgrade.tipintro': { en: 'Unlock all PRO features', es: 'Desbloquear todas las funciones PRO', zh: '解锁所有 PRO 功能', 'zh-TW': '解鎖所有 PRO 功能' },
    'app.upgrade.tipbtn': { en: 'Upgrade to PRO', es: 'Actualizar a PRO', zh: '升级到 PRO', 'zh-TW': '升級到 PRO' },
    'app.waitlist.intro': { en: 'The coming features are being developed. Stay tuned!', es: 'Se están desarrollando las características próximas.¡Manténganse al tanto!', zh: '即将推出的功能正在开发中，敬请关注！', 'zh-TW': '即將推出的功能正在開發中，敬請關注！' },
    'app.waitlist.btn': { en: 'Join the waiting list', es: 'Join the waiting list', zh: '加入等待列表' },
    'app.mark.head': { en: 'Marks', es: 'Marcas', zh: '标记', 'zh-TW': '標記' },
    'app.print.title': { en: 'Print / Export PDF', es: 'Imprimir | Exportar PDF', zh: '打印 / 导出 PDF', 'zh-TW': '打印 / 導出 PDF' },
    'app.print.withoutline': { en: 'With outline', es: 'Con esquema', zh: '带大纲', 'zh-TW': '帶大綱' },
    'app.print.withmark': { en: 'Highlight marks', es: 'Resaltar marcas', zh: '高亮标记', 'zh-TW': '高亮標記' },
    'app.print.withoutmeta': { en: 'Remove author, words count, etc.', es: 'Eliminar autor, número de palabras, etc.', zh: '移除作者、字数等信息', 'zh-TW': '移除作者、字數等信息' },
    'app.print.btn': { en: 'Print/Export PDF', es: 'Imprimir/Exportar PDF', zh: '打印/导出 PDF', 'zh-TW': '打印/導出 PDF' },
    'app.clip.allclips': { en: 'All CLIPs', es: 'Todos los clips', zh: '所有 CLIP', 'zh-TW': '所有CLIP' },
    'app.clip.nodata': { en: 'No clips yet', es: 'No hay clips todavía', zh: '还没有 CLIP', 'zh-TW': '還沒有 CLIP' },
    'app.clip.currentclip': { en: 'Current CLIP', es: 'Clip actual', zh: '当前 CLIP', 'zh-TW': '當前 CLIP' },
    'app.clip.currenttab': { en: 'Current', es: 'Actual', zh: '当前', 'zh-TW': '當前' },
    'app.clip.bookmarkstab': { en: 'Bookmarks', es: 'Marcadores', zh: '书签', 'zh-TW': '書籤' },
    'app.clip.markstab': { en: 'Marks', es: 'Marcas', zh: '标记', 'zh-TW': '標記' },
    'app.clip.cliptab': { en: 'CLIP', es: 'CLIP', zh: '剪藏', 'zh-TW': '剪藏' },
    'app.clip.rsstab': { en: 'RSS', es: 'RSS', zh: 'RSS', 'zh-TW': 'RSS' },
    'app.clip.podcasttab': { en: 'Podcasts', es: 'Podcasts', zh: '播客', 'zh-TW': '播客' },
    'app.clip.webappavaiable': { en: 'Web app is available. Visit now.', es: 'La aplicación web está disponible. Visítala ahora.', zh: 'Web 应用已上线，现在就去体验。', 'zh-TW': 'Web 應用已上線，現在就去體驗。' },
    'app.clip.usewebapp': { en: 'Use Web App', es: 'Usar la aplicación web', zh: '使用 Web 应用', 'zh-TW': '使用 Web 應用' },
    'app.summary.footer': { en: 'Powered by OpenAI', es: 'Powered by OpenAI', zh: '由 OpenAI 提供技术支持', 'zh-TW': '由 OpenAI 提供技術支持' },
    'app.alert.btn': { en: 'Check', es: 'Comprobar', zh: '查看', 'zh-TW': '查看' }
  },

  alias: {
    'zh-CN': 'zh',
    'zh-HK': 'zh-TW',
    'zh-MO': 'zh-TW',
    'zh-CHS': 'zh-TW'
  },

  get (key, lang, ...values) {
    const messages = CLEARLY_MESSAGE.messages[key]
    if (!messages) return key
    lang = CLEARLY_MESSAGE.alias[lang] || lang

    const mainLang = lang.split('-').shift()
    const text = messages[lang] || messages[mainLang] || messages.en
    if (text.includes('$')) {
      return text.replace(/\$([\d])/g, (_, id) => values[Number(id) - 1])
    }
    return text
  }
}

window.CLEARLY_MESSAGE = CLEARLY_MESSAGE

if (typeof module === 'object') {
  module.exports = CLEARLY_MESSAGE
}
